package com.singularitycoder.systembroadcasts

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import com.singularitycoder.systembroadcasts.AppUtils.buildNotification

class SystemEventReceiver : BroadcastReceiver() {

    override fun onReceive(context: Context, intent: Intent) {
        // This method is called when the BroadcastReceiver is receiving an Intent broadcast.
        // This check will prevent other apps from calling BOOT_COMPLETED on this Receiver simply by specifying the classname.
        when(intent.action) {
            Intent.ACTION_POWER_CONNECTED -> buildNotification(context = context, notificationId = 0, intentType = Intent.ACTION_POWER_CONNECTED)
            Intent.ACTION_POWER_DISCONNECTED -> buildNotification(context = context, notificationId = 1, intentType = Intent.ACTION_POWER_DISCONNECTED)
            Intent.ACTION_SHUTDOWN -> buildNotification(context = context, notificationId = 2, intentType = Intent.ACTION_SHUTDOWN)
            Intent.ACTION_AIRPLANE_MODE_CHANGED -> buildNotification(context = context, notificationId = 3, intentType = Intent.ACTION_AIRPLANE_MODE_CHANGED)
            Intent.ACTION_APPLICATION_RESTRICTIONS_CHANGED -> buildNotification(context = context, notificationId = 4, intentType = Intent.ACTION_APPLICATION_RESTRICTIONS_CHANGED)
            Intent.ACTION_BATTERY_CHANGED -> buildNotification(context = context, notificationId = 5, intentType = Intent.ACTION_BATTERY_CHANGED)
            Intent.ACTION_BATTERY_LOW -> buildNotification(context = context, notificationId = 6, intentType = Intent.ACTION_BATTERY_LOW)
            Intent.ACTION_BATTERY_OKAY -> buildNotification(context = context, notificationId = 7, intentType = Intent.ACTION_BATTERY_OKAY)
            Intent.ACTION_CAMERA_BUTTON -> buildNotification(context = context, notificationId = 8, intentType = Intent.ACTION_CAMERA_BUTTON)
            Intent.ACTION_CLOSE_SYSTEM_DIALOGS -> buildNotification(context = context, notificationId = 9, intentType = Intent.ACTION_CLOSE_SYSTEM_DIALOGS)
            Intent.ACTION_CONFIGURATION_CHANGED -> buildNotification(context = context, notificationId = 10, intentType = Intent.ACTION_CONFIGURATION_CHANGED)
            Intent.ACTION_DATE_CHANGED -> buildNotification(context = context, notificationId = 11, intentType = Intent.ACTION_DATE_CHANGED)
            Intent.ACTION_DEVICE_STORAGE_LOW -> buildNotification(context = context, notificationId = 12, intentType = Intent.ACTION_DEVICE_STORAGE_LOW)
            Intent.ACTION_DEVICE_STORAGE_OK -> buildNotification(context = context, notificationId = 13, intentType = Intent.ACTION_DEVICE_STORAGE_OK)
            Intent.ACTION_DOCK_EVENT -> buildNotification(context = context, notificationId = 14, intentType = Intent.ACTION_DOCK_EVENT)
            Intent.ACTION_DREAMING_STARTED -> buildNotification(context = context, notificationId = 15, intentType = Intent.ACTION_DREAMING_STARTED)
            Intent.ACTION_DREAMING_STOPPED -> buildNotification(context = context, notificationId = 16, intentType = Intent.ACTION_DREAMING_STOPPED)
            Intent.ACTION_EXTERNAL_APPLICATIONS_AVAILABLE -> buildNotification(context = context, notificationId = 17, intentType = Intent.ACTION_EXTERNAL_APPLICATIONS_AVAILABLE)
            Intent.ACTION_EXTERNAL_APPLICATIONS_UNAVAILABLE -> buildNotification(context = context, notificationId = 18, intentType = Intent.ACTION_EXTERNAL_APPLICATIONS_UNAVAILABLE)
            Intent.ACTION_GTALK_SERVICE_CONNECTED -> buildNotification(context = context, notificationId = 19, intentType = Intent.ACTION_GTALK_SERVICE_CONNECTED)
            Intent.ACTION_GTALK_SERVICE_DISCONNECTED -> buildNotification(context = context, notificationId = 20, intentType = Intent.ACTION_GTALK_SERVICE_DISCONNECTED)
            Intent.ACTION_HEADSET_PLUG -> buildNotification(context = context, notificationId = 21, intentType = Intent.ACTION_HEADSET_PLUG)
            Intent.ACTION_INPUT_METHOD_CHANGED -> buildNotification(context = context, notificationId = 22, intentType = Intent.ACTION_INPUT_METHOD_CHANGED)
            Intent.ACTION_LOCALE_CHANGED -> buildNotification(context = context, notificationId = 23, intentType = Intent.ACTION_LOCALE_CHANGED)
            Intent.ACTION_LOCKED_BOOT_COMPLETED -> buildNotification(context = context, notificationId = 24, intentType = Intent.ACTION_LOCKED_BOOT_COMPLETED)
            Intent.ACTION_MANAGE_PACKAGE_STORAGE -> buildNotification(context = context, notificationId = 25, intentType = Intent.ACTION_MANAGE_PACKAGE_STORAGE)
            Intent.ACTION_MEDIA_BAD_REMOVAL -> buildNotification(context = context, notificationId = 26, intentType = Intent.ACTION_MEDIA_BAD_REMOVAL)
            Intent.ACTION_MEDIA_BUTTON -> buildNotification(context = context, notificationId = 27, intentType = Intent.ACTION_MEDIA_BUTTON)
            Intent.ACTION_MEDIA_CHECKING -> buildNotification(context = context, notificationId = 28, intentType = Intent.ACTION_MEDIA_CHECKING)
            Intent.ACTION_MEDIA_EJECT -> buildNotification(context = context, notificationId = 29, intentType = Intent.ACTION_MEDIA_EJECT)
            Intent.ACTION_MEDIA_MOUNTED -> buildNotification(context = context, notificationId = 30, intentType = Intent.ACTION_MEDIA_MOUNTED)
            Intent.ACTION_MEDIA_NOFS -> buildNotification(context = context, notificationId = 31, intentType = Intent.ACTION_MEDIA_NOFS)
            Intent.ACTION_MEDIA_REMOVED -> buildNotification(context = context, notificationId = 32, intentType = Intent.ACTION_MEDIA_REMOVED)
            Intent.ACTION_MEDIA_SCANNER_FINISHED -> buildNotification(context = context, notificationId = 33, intentType = Intent.ACTION_MEDIA_SCANNER_FINISHED)
            Intent.ACTION_MEDIA_SCANNER_SCAN_FILE -> buildNotification(context = context, notificationId = 34, intentType = Intent.ACTION_MEDIA_SCANNER_SCAN_FILE)
            Intent.ACTION_MEDIA_SCANNER_STARTED -> buildNotification(context = context, notificationId = 35, intentType = Intent.ACTION_MEDIA_SCANNER_STARTED)
            Intent.ACTION_MEDIA_SHARED -> buildNotification(context = context, notificationId = 36, intentType = Intent.ACTION_MEDIA_SHARED)
            Intent.ACTION_MEDIA_UNMOUNTABLE -> buildNotification(context = context, notificationId = 37, intentType = Intent.ACTION_MEDIA_UNMOUNTABLE)
            Intent.ACTION_MEDIA_UNMOUNTED -> buildNotification(context = context, notificationId = 38, intentType = Intent.ACTION_MEDIA_UNMOUNTED)
            Intent.ACTION_MY_PACKAGE_REPLACED -> buildNotification(context = context, notificationId = 39, intentType = Intent.ACTION_MY_PACKAGE_REPLACED)
            Intent.ACTION_MY_PACKAGE_SUSPENDED -> buildNotification(context = context, notificationId = 40, intentType = Intent.ACTION_MY_PACKAGE_SUSPENDED)
            Intent.ACTION_MY_PACKAGE_UNSUSPENDED -> buildNotification(context = context, notificationId = 41, intentType = Intent.ACTION_MY_PACKAGE_UNSUSPENDED)
            Intent.ACTION_NEW_OUTGOING_CALL -> buildNotification(context = context, notificationId = 42, intentType = Intent.ACTION_NEW_OUTGOING_CALL)
            Intent.ACTION_PACKAGE_ADDED -> buildNotification(context = context, notificationId = 43, intentType = Intent.ACTION_PACKAGE_ADDED)
            Intent.ACTION_PACKAGE_CHANGED -> buildNotification(context = context, notificationId = 44, intentType = Intent.ACTION_PACKAGE_CHANGED)
            Intent.ACTION_PACKAGE_DATA_CLEARED -> buildNotification(context = context, notificationId = 45, intentType = Intent.ACTION_PACKAGE_DATA_CLEARED)
            Intent.ACTION_PACKAGE_FIRST_LAUNCH -> buildNotification(context = context, notificationId = 46, intentType = Intent.ACTION_PACKAGE_FIRST_LAUNCH)
            Intent.ACTION_PACKAGE_FULLY_REMOVED -> buildNotification(context = context, notificationId = 47, intentType = Intent.ACTION_PACKAGE_FULLY_REMOVED)
            Intent.ACTION_PACKAGE_INSTALL -> buildNotification(context = context, notificationId = 48, intentType = Intent.ACTION_PACKAGE_INSTALL)
            Intent.ACTION_PACKAGE_NEEDS_VERIFICATION -> buildNotification(context = context, notificationId = 49, intentType = Intent.ACTION_PACKAGE_NEEDS_VERIFICATION)
            Intent.ACTION_PACKAGE_REMOVED -> buildNotification(context = context, notificationId = 50, intentType = Intent.ACTION_PACKAGE_REMOVED)
            Intent.ACTION_PACKAGE_REPLACED -> buildNotification(context = context, notificationId = 51, intentType = Intent.ACTION_PACKAGE_REPLACED)
            Intent.ACTION_PACKAGE_RESTARTED -> buildNotification(context = context, notificationId = 52, intentType = Intent.ACTION_PACKAGE_RESTARTED)
            Intent.ACTION_PACKAGE_VERIFIED -> buildNotification(context = context, notificationId = 53, intentType = Intent.ACTION_PACKAGE_VERIFIED)
            Intent.ACTION_PACKAGES_SUSPENDED -> buildNotification(context = context, notificationId = 54, intentType = Intent.ACTION_PACKAGES_SUSPENDED)
            Intent.ACTION_PACKAGES_UNSUSPENDED -> buildNotification(context = context, notificationId = 55, intentType = Intent.ACTION_PACKAGES_UNSUSPENDED)
            Intent.ACTION_PROVIDER_CHANGED -> buildNotification(context = context, notificationId = 56, intentType = Intent.ACTION_PROVIDER_CHANGED)
            Intent.ACTION_REBOOT -> buildNotification(context = context, notificationId = 57, intentType = Intent.ACTION_REBOOT)
            Intent.ACTION_SCREEN_OFF -> buildNotification(context = context, notificationId = 58, intentType = Intent.ACTION_SCREEN_OFF)
            Intent.ACTION_SCREEN_ON -> buildNotification(context = context, notificationId = 59, intentType = Intent.ACTION_SCREEN_ON)
            Intent.ACTION_TIME_CHANGED -> buildNotification(context = context, notificationId = 60, intentType = Intent.ACTION_TIME_CHANGED)
            Intent.ACTION_TIME_TICK -> buildNotification(context = context, notificationId = 61, intentType = Intent.ACTION_TIME_TICK)
            Intent.ACTION_TIMEZONE_CHANGED -> buildNotification(context = context, notificationId = 62, intentType = Intent.ACTION_TIMEZONE_CHANGED)
            Intent.ACTION_UID_REMOVED -> buildNotification(context = context, notificationId = 63, intentType = Intent.ACTION_UID_REMOVED)
            Intent.ACTION_UMS_CONNECTED -> buildNotification(context = context, notificationId = 64, intentType = Intent.ACTION_UMS_CONNECTED)
            Intent.ACTION_UMS_DISCONNECTED -> buildNotification(context = context, notificationId = 65, intentType = Intent.ACTION_UMS_DISCONNECTED)
            Intent.ACTION_USER_PRESENT -> buildNotification(context = context, notificationId = 66, intentType = Intent.ACTION_USER_PRESENT)
            Intent.ACTION_USER_UNLOCKED -> buildNotification(context = context, notificationId = 67, intentType = Intent.ACTION_USER_UNLOCKED)
            Intent.ACTION_WALLPAPER_CHANGED -> buildNotification(context = context, notificationId = 68, intentType = Intent.ACTION_WALLPAPER_CHANGED)
            Intent.ACTION_BOOT_COMPLETED -> buildNotification(context = context, notificationId = 69, intentType = Intent.ACTION_BOOT_COMPLETED)
        }
    }
}